packages:
  - 'apps/electron-example'
  - 'apps/electron-minimal'
  - 'apps/tauri-example'
  - 'apps/tauri-v1-example'
  - 'e2e'
  - 'packages/electron'
  - 'packages/tauri'
  - 'packages/tauri-plugin-zubridge'
  - 'packages/types'
  - 'packages/ui'
