name: Manual Release Publish

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to release from'
        required: true
        default: 'main' # Default to main for most common case
        type: choice
        options:
          - main # Current stable
          - feature # Next major development
      release_version:
        description: 'Release type - patch, minor, or major'
        required: true
        default: 'patch'
        type: choice
        options: ['patch', 'minor', 'major']
      packages:
        description: 'Package(s) to release'
        required: true
        default: 'all'
        type: choice
        options:
          - '@zubridge/electron'
          - '@zubridge/tauri'
          - '@zubridge/types'
          - 'all'
      dry_run:
        description: 'Do not touch or write anything. Show the commands.'
        required: true
        default: false
        type: boolean

jobs:
  release:
    name: Release
    uses: ./.github/workflows/_release-orchestration.reusable.yml
    with:
      branch: ${{ inputs.branch }}
      release_version: ${{ inputs.release_version }}
      packages: ${{ inputs.packages }}
      dry_run: ${{ inputs.dry_run }}
    secrets:
      github_bot_token: ${{ secrets.GITHUB_TOKEN }}
      npm_token: ${{ secrets.NPM_TOKEN }}
      deploy_key: ${{ secrets.DEPLOY_KEY }}
